# Buildpack API version
api = "0.2"

[buildpack]
id = "buildpacks/empty"
version = "0.0.1"
name = "Empty Buildpack"
homepage = "https://github.com/tmtk75/buildpack-sample"

[[stacks]]
id = "io.github.tmtk75.buildpack-sample.1"

